"""
AWS Cognito Service Module

Centralized imports for AWS Cognito compliance checks.
"""

# Import the service class
from .cognito_service import CognitoService

# Import individual checks
from .cognito_identity_pool_guest_access_disabled.cognito_identity_pool_guest_access_disabled import cognito_identity_pool_guest_access_disabled
from .cognito_user_pool_advanced_security_enabled.cognito_user_pool_advanced_security_enabled import cognito_user_pool_advanced_security_enabled
from .cognito_user_pool_blocks_compromised_credentials_sign_in_attempts.cognito_user_pool_blocks_compromised_credentials_sign_in_attempts import cognito_user_pool_blocks_compromised_credentials_sign_in_attempts
from .cognito_user_pool_blocks_potential_malicious_sign_in_attempts.cognito_user_pool_blocks_potential_malicious_sign_in_attempts import cognito_user_pool_blocks_potential_malicious_sign_in_attempts
from .cognito_user_pool_client_prevent_user_existence_errors.cognito_user_pool_client_prevent_user_existence_errors import cognito_user_pool_client_prevent_user_existence_errors
from .cognito_user_pool_client_token_revocation_enabled.cognito_user_pool_client_token_revocation_enabled import cognito_user_pool_client_token_revocation_enabled
from .cognito_user_pool_deletion_protection_enabled.cognito_user_pool_deletion_protection_enabled import cognito_user_pool_deletion_protection_enabled
from .cognito_user_pool_mfa_enabled.cognito_user_pool_mfa_enabled import cognito_user_pool_mfa_enabled
from .cognito_user_pool_password_policy_lowercase.cognito_user_pool_password_policy_lowercase import cognito_user_pool_password_policy_lowercase
from .cognito_user_pool_password_policy_minimum_length_14.cognito_user_pool_password_policy_minimum_length_14 import cognito_user_pool_password_policy_minimum_length_14
from .cognito_user_pool_password_policy_number.cognito_user_pool_password_policy_number import cognito_user_pool_password_policy_number
from .cognito_user_pool_password_policy_symbol.cognito_user_pool_password_policy_symbol import cognito_user_pool_password_policy_symbol
from .cognito_user_pool_password_policy_uppercase.cognito_user_pool_password_policy_uppercase import cognito_user_pool_password_policy_uppercase
from .cognito_user_pool_self_registration_disabled.cognito_user_pool_self_registration_disabled import cognito_user_pool_self_registration_disabled
from .cognito_user_pool_temporary_password_expiration.cognito_user_pool_temporary_password_expiration import cognito_user_pool_temporary_password_expiration
from .cognito_user_pool_waf_acl_attached.cognito_user_pool_waf_acl_attached import cognito_user_pool_waf_acl_attached

__all__ = [
    'CognitoService',
    'cognito_identity_pool_guest_access_disabled',
    'cognito_user_pool_advanced_security_enabled',
    'cognito_user_pool_blocks_compromised_credentials_sign_in_attempts',
    'cognito_user_pool_blocks_potential_malicious_sign_in_attempts',
    'cognito_user_pool_client_prevent_user_existence_errors',
    'cognito_user_pool_client_token_revocation_enabled',
    'cognito_user_pool_deletion_protection_enabled',
    'cognito_user_pool_mfa_enabled',
    'cognito_user_pool_password_policy_lowercase',
    'cognito_user_pool_password_policy_minimum_length_14',
    'cognito_user_pool_password_policy_number',
    'cognito_user_pool_password_policy_symbol',
    'cognito_user_pool_password_policy_uppercase',
    'cognito_user_pool_self_registration_disabled',
    'cognito_user_pool_temporary_password_expiration',
    'cognito_user_pool_waf_acl_attached',
]
