"""
AWS Cloudfront Service Module

Centralized imports for AWS Cloudfront compliance checks.
"""

# Import the service class
from .cloudfront_service import CloudFrontService

# Import individual checks
from .cloudfront_distributions_custom_ssl_certificate.cloudfront_distributions_custom_ssl_certificate import cloudfront_distributions_custom_ssl_certificate
from .cloudfront_distributions_default_root_object.cloudfront_distributions_default_root_object import cloudfront_distributions_default_root_object
from .cloudfront_distributions_field_level_encryption_enabled.cloudfront_distributions_field_level_encryption_enabled import cloudfront_distributions_field_level_encryption_enabled
from .cloudfront_distributions_geo_restrictions_enabled.cloudfront_distributions_geo_restrictions_enabled import cloudfront_distributions_geo_restrictions_enabled
from .cloudfront_distributions_https_enabled.cloudfront_distributions_https_enabled import cloudfront_distributions_https_enabled
from .cloudfront_distributions_https_sni_enabled.cloudfront_distributions_https_sni_enabled import cloudfront_distributions_https_sni_enabled
from .cloudfront_distributions_logging_enabled.cloudfront_distributions_logging_enabled import cloudfront_distributions_logging_enabled
from .cloudfront_distributions_multiple_origin_failover_configured.cloudfront_distributions_multiple_origin_failover_configured import cloudfront_distributions_multiple_origin_failover_configured
from .cloudfront_distributions_origin_traffic_encrypted.cloudfront_distributions_origin_traffic_encrypted import cloudfront_distributions_origin_traffic_encrypted
from .cloudfront_distributions_s3_origin_access_control.cloudfront_distributions_s3_origin_access_control import cloudfront_distributions_s3_origin_access_control
from .cloudfront_distributions_s3_origin_non_existent_bucket.cloudfront_distributions_s3_origin_non_existent_bucket import cloudfront_distributions_s3_origin_non_existent_bucket
from .cloudfront_distributions_using_deprecated_ssl_protocols.cloudfront_distributions_using_deprecated_ssl_protocols import cloudfront_distributions_using_deprecated_ssl_protocols
from .cloudfront_distributions_using_waf.cloudfront_distributions_using_waf import cloudfront_distributions_using_waf

__all__ = [
    'CloudFrontService',
    'cloudfront_distributions_custom_ssl_certificate',
    'cloudfront_distributions_default_root_object',
    'cloudfront_distributions_field_level_encryption_enabled',
    'cloudfront_distributions_geo_restrictions_enabled',
    'cloudfront_distributions_https_enabled',
    'cloudfront_distributions_https_sni_enabled',
    'cloudfront_distributions_logging_enabled',
    'cloudfront_distributions_multiple_origin_failover_configured',
    'cloudfront_distributions_origin_traffic_encrypted',
    'cloudfront_distributions_s3_origin_access_control',
    'cloudfront_distributions_s3_origin_non_existent_bucket',
    'cloudfront_distributions_using_deprecated_ssl_protocols',
    'cloudfront_distributions_using_waf',
]
