"""
AWS Opensearch Service Module

Centralized imports for AWS Opensearch compliance checks.
"""

# Import the service class
from .opensearch_service import OpenSearchService

# Import individual checks
from .opensearch_service_domains_access_control_enabled.opensearch_service_domains_access_control_enabled import opensearch_service_domains_access_control_enabled
from .opensearch_service_domains_audit_logging_enabled.opensearch_service_domains_audit_logging_enabled import opensearch_service_domains_audit_logging_enabled
from .opensearch_service_domains_cloudwatch_logging_enabled.opensearch_service_domains_cloudwatch_logging_enabled import opensearch_service_domains_cloudwatch_logging_enabled
from .opensearch_service_domains_encryption_at_rest_enabled.opensearch_service_domains_encryption_at_rest_enabled import opensearch_service_domains_encryption_at_rest_enabled
from .opensearch_service_domains_fault_tolerant_data_nodes.opensearch_service_domains_fault_tolerant_data_nodes import opensearch_service_domains_fault_tolerant_data_nodes
from .opensearch_service_domains_fault_tolerant_master_nodes.opensearch_service_domains_fault_tolerant_master_nodes import opensearch_service_domains_fault_tolerant_master_nodes
from .opensearch_service_domains_https_communications_enforced.opensearch_service_domains_https_communications_enforced import opensearch_service_domains_https_communications_enforced
from .opensearch_service_domains_internal_user_database_enabled.opensearch_service_domains_internal_user_database_enabled import opensearch_service_domains_internal_user_database_enabled
from .opensearch_service_domains_node_to_node_encryption_enabled.opensearch_service_domains_node_to_node_encryption_enabled import opensearch_service_domains_node_to_node_encryption_enabled
from .opensearch_service_domains_not_publicly_accessible.opensearch_service_domains_not_publicly_accessible import opensearch_service_domains_not_publicly_accessible
from .opensearch_service_domains_updated_to_the_latest_service_software_version.opensearch_service_domains_updated_to_the_latest_service_software_version import opensearch_service_domains_updated_to_the_latest_service_software_version
from .opensearch_service_domains_use_cognito_authentication_for_kibana.opensearch_service_domains_use_cognito_authentication_for_kibana import opensearch_service_domains_use_cognito_authentication_for_kibana

__all__ = [
    'OpenSearchService',
    'opensearch_service_domains_access_control_enabled',
    'opensearch_service_domains_audit_logging_enabled',
    'opensearch_service_domains_cloudwatch_logging_enabled',
    'opensearch_service_domains_encryption_at_rest_enabled',
    'opensearch_service_domains_fault_tolerant_data_nodes',
    'opensearch_service_domains_fault_tolerant_master_nodes',
    'opensearch_service_domains_https_communications_enforced',
    'opensearch_service_domains_internal_user_database_enabled',
    'opensearch_service_domains_node_to_node_encryption_enabled',
    'opensearch_service_domains_not_publicly_accessible',
    'opensearch_service_domains_updated_to_the_latest_service_software_version',
    'opensearch_service_domains_use_cognito_authentication_for_kibana',
]
