apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-recommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-recommendation
  template:
    metadata:
      labels:
        app: ai-recommendation
    spec:
      containers:
      - name: ai-recommendation
        image: ai-recommendation:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ai-recommendation
spec:
  selector:
    app: ai-recommendation
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP