apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-engine
  template:
    metadata:
      labels:
        app: alert-engine
    spec:
      containers:
      - name: alert-engine
        image: alert-engine:latest
        ports:
        - containerPort:3000
---
apiVersion: v1
kind: Service
metadata:
  name: alert-engine
spec:
  selector:
    app: alert-engine
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP