apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-connector
  template:
    metadata:
      labels:
        app: cloud-connector
    spec:
      containers:
      - name: cloud-connector
        image: cloud-connector:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-connector
spec:
  selector:
    app: cloud-connector
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP