apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliance-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compliance-engine
  template:
    metadata:
      labels:
        app: compliance-engine
    spec:
      containers:
      - name: compliance-engine
        image: compliance-engine:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: compliance-engine
spec:
  selector:
    app: compliance-engine
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP