apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-security
  template:
    metadata:
      labels:
        app: data-security
    spec:
      containers:
      - name: data-security
        image: data-security:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: data-security
spec:
  selector:
    app: data-security
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP