apiVersion: apps/v1
kind: Deployment
metadata:
  name: drift-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drift-detection
  template:
    metadata:
      labels:
        app: drift-detection
    spec:
      containers:
      - name: drift-detection
        image: drift-detection:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: drift-detection
spec:
  selector:
    app: drift-detection
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP