apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-collector
  template:
    metadata:
      labels:
        app: inventory-collector
    spec:
      containers:
      - name: inventory-collector
        image: inventory-collector:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-collector
spec:
  selector:
    app: inventory-collector
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP