apiVersion: apps/v1
kind: Deployment
metadata:
  name: threat-intelligence
spec:
  replicas: 1
  selector:
    matchLabels:
      app: threat-intelligence
  template:
    metadata:
      labels:
        app: threat-intelligence
    spec:
      containers:
      - name: threat-intelligence
        image: threat-intelligence:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: threat-intelligence
spec:
  selector:
    app: threat-intelligence
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP